import React, { Component } from 'react';

export class NewsBody extends Component {
    render() {
        return (
            <div className='news'>
                <h1>Test</h1>
                <p>
                
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec fringilla dictum enim, ac interdum eros molestie eget. Mauris cursus tempor lectus vel eleifend. Ut non eleifend tellus, sed eleifend tellus. Vivamus lectus orci, tristique sit amet hendrerit sit amet, dignissim et enim. Sed ut tincidunt libero, in venenatis nisi. Ut porta ullamcorper sodales. Proin et pharetra lorem. Nam rhoncus molestie nisl a venenatis. Integer et lacinia dui. Nullam rhoncus nisl sit amet tincidunt tincidunt. Phasellus magna augue, commodo nec magna sed, semper pretium justo. Aenean gravida, orci sit amet cursus ullamcorper, mauris arcu sagittis orci, ac ultricies erat nulla ut urna.
                
                Praesent pellentesque fringilla pretium. Proin pellentesque lorem ut nunc elementum vehicula. Mauris fermentum id elit quis gravida. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque vel sagittis velit, eu fringilla odio. Nullam eu volutpat dolor, gravida aliquet nunc. Nulla gravida leo eu libero pretium, vel aliquet odio elementum. Morbi dignissim scelerisque nunc. Nam rhoncus, augue vel accumsan commodo, metus ex mollis orci, auctor euismod arcu leo at justo.
                
                Duis molestie ipsum sed augue condimentum, id mattis nibh faucibus. Integer maximus massa purus, eget tristique eros pellentesque eu. Phasellus tincidunt est et luctus congue. Suspendisse laoreet quam vitae enim elementum tristique. Sed dignissim ante non ante tempor imperdiet at ut massa. Pellentesque tellus justo, pulvinar eget ante ut, ultrices pulvinar est. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean eget tellus eu lectus iaculis tincidunt at quis magna.
                
                Praesent cursus tincidunt mauris, nec imperdiet risus pretium sed. Etiam eget mauris vitae turpis egestas efficitur eget vel mauris. Proin luctus dignissim tortor mollis convallis. Pellentesque at dolor vulputate dolor sodales consectetur nec eu ligula. Vestibulum lobortis purus non ligula condimentum auctor. Fusce laoreet laoreet ante, ac facilisis ligula. Duis non consectetur nisl. Suspendisse potenti. Maecenas tincidunt magna in augue semper varius sed in purus. Morbi quam enim, malesuada ac augue eu, cursus congue ex. Duis varius nisl dui, in auctor est tempus non. Curabitur mollis, justo at facilisis molestie, arcu mi pharetra justo, et mollis felis nisi id nunc.
                
                Donec eleifend odio elit, sed dapibus dui porttitor in. Cras scelerisque lacus id nisl aliquam interdum. Nunc gravida diam eget lectus lacinia, id finibus ante pellentesque. Mauris ultricies ante ut magna lacinia, iaculis ullamcorper purus tincidunt. Curabitur aliquet mollis porta. Nullam nisi diam, rhoncus sit amet vehicula non, dignissim sed est. Nullam at fringilla tellus, vel malesuada ligula. Maecenas eget nisl bibendum, faucibus erat ut, lobortis augue. Duis vestibulum interdum eros eget posuere. Nunc sit amet arcu ac sem mollis finibus eu euismod erat.
                
                Mauris dapibus mauris feugiat enim pharetra, nec semper quam fringilla. In eu pellentesque felis. Donec cursus molestie augue, at convallis ligula euismod at. Cras at fermentum urna, sed sollicitudin nibh. Aliquam elit dolor, consectetur eu dolor nec, interdum porta erat. Suspendisse et augue pellentesque, commodo risus ut, fermentum elit. Praesent diam lectus, ullamcorper quis nunc eu, commodo pulvinar nunc. Phasellus lobortis, nisl varius lacinia interdum, purus magna volutpat erat, vitae pharetra sapien felis sit amet massa. Fusce at mattis nisi. Pellentesque magna purus, tristique in condimentum sit amet, vulputate gravida orci. In risus dolor, auctor vitae quam non, bibendum molestie tortor. Praesent feugiat mauris nec nisl rhoncus porttitor. In luctus, ligula quis tempus maximus, lorem augue accumsan ligula, eget tempus libero elit quis tellus. Quisque egestas lacinia odio, vitae lobortis lectus tincidunt quis. Nam dictum ligula vel nibh fringilla, quis fermentum massa fermentum.
                
                Nulla egestas purus purus, quis sollicitudin tellus blandit et. Donec et fermentum libero. Nam iaculis mollis ultricies. Donec nec pharetra elit, varius bibendum velit. Nam viverra faucibus libero in pharetra. Etiam eget nisi tortor. Pellentesque sit amet eleifend dolor, ac lacinia arcu. Phasellus luctus, nisi vel laoreet egestas, velit neque efficitur ex, sit amet tincidunt ligula tellus vitae augue. Proin mollis venenatis eros, non consequat lorem porta et. Proin imperdiet rhoncus augue eu interdum. Maecenas ut est nec lectus fermentum viverra. Fusce eget enim augue. Mauris quis euismod massa, id iaculis massa. Maecenas sollicitudin mauris eu vulputate porttitor. Donec at neque nec ligula maximus cursus. Morbi magna lorem, lobortis tempor metus eu, viverra ornare nisi.
                
                Cras aliquam nisi metus, non mollis ante lobortis eu. Mauris risus turpis, tristique a lorem vehicula, pulvinar feugiat quam. Etiam quis enim eu orci viverra placerat in vitae quam. Praesent blandit ac est vitae interdum. Donec condimentum purus in leo cursus finibus. Fusce dignissim sollicitudin magna et suscipit. Morbi nec justo aliquam erat maximus euismod. Nulla vitae volutpat arcu. Fusce interdum et ex et euismod. Mauris non congue elit, vel efficitur massa. Nullam lacinia ullamcorper mollis. Nulla sit amet eros blandit, sodales magna at, condimentum ante. Integer sit amet euismod urna, ut finibus ligula. Vivamus venenatis ut justo vitae eleifend. Suspendisse posuere neque at efficitur fringilla.
                
                In iaculis consectetur elit, at pulvinar risus condimentum ac. Donec pretium placerat metus bibendum fringilla. Curabitur interdum quis velit nec egestas. Aliquam erat volutpat. Nulla facilisi. Nam varius sed dolor et tempor. Donec in augue vitae eros tempor faucibus. In dictum feugiat lacus ac accumsan. Morbi ultrices sagittis enim non congue. Sed molestie, nisi sit amet vulputate scelerisque, lectus enim vulputate enim, id semper augue sapien vitae ligula. Praesent pellentesque scelerisque leo, suscipit porttitor felis mollis vitae. Donec a augue a mauris luctus scelerisque. Curabitur velit mi, sagittis id maximus eget, commodo ut purus. Aenean rhoncus ipsum vel vulputate cursus. Integer eget dignissim diam.
                
                Donec id purus finibus ante mattis sodales aliquam a libero. Phasellus pulvinar vulputate arcu a faucibus. Nam varius quam libero, non vestibulum est pulvinar malesuada. Suspendisse egestas lacus convallis ante posuere rutrum. Morbi consectetur sollicitudin tristique. Ut sem metus, placerat ut tincidunt accumsan, porta ut erat. Nunc neque ex, sagittis vitae augue a, maximus tempor elit.
                
                Nunc ornare, urna id maximus consequat, ligula diam rhoncus justo, ut vestibulum dui massa ut massa. Aliquam pulvinar dui sed ipsum finibus, eu laoreet magna luctus. Fusce cursus eget velit scelerisque varius. Suspendisse dignissim posuere lectus vel pulvinar. Sed luctus est nunc, at congue leo convallis ac. Cras pellentesque metus vel metus hendrerit laoreet at a lorem. Nulla facilisi. Duis non facilisis velit. Aenean mi arcu, ultricies posuere turpis sit amet, pellentesque pellentesque mauris.
                
                Proin mattis at sapien at posuere. Proin at nunc elit. Phasellus iaculis sit amet risus id porta. Suspendisse congue fringilla felis sit amet commodo. Nunc ultricies massa eu metus tempor molestie. Fusce elementum feugiat eros, vitae tempus velit accumsan eu. Phasellus consectetur, nunc at blandit luctus, odio urna egestas quam, at hendrerit ligula enim eget turpis. Mauris vulputate diam ex, eget pellentesque neque elementum sit amet. Cras luctus imperdiet nulla, vel consectetur justo.
                
                Maecenas justo nunc, pellentesque eu suscipit et, dapibus eget justo. Morbi sed molestie orci. Nam vitae mi at risus sollicitudin porttitor. Aenean tempus viverra pulvinar. Etiam malesuada vitae elit quis laoreet. Pellentesque consectetur, odio sed ultricies semper, lectus dui feugiat est, non porttitor leo ligula eget dui. Vivamus et risus vestibulum, congue odio eget, condimentum arcu. Vivamus dui tortor, tempor id tempor non, mattis nec ante. Aliquam erat volutpat. Integer nec nisl lacinia, volutpat sem ac, ornare erat. Nam ultricies dolor vel turpis luctus, sit amet suscipit nisl aliquet. Suspendisse a erat eu sem feugiat ultrices.
                
                Etiam laoreet nibh est, sit amet lobortis odio accumsan ac. Etiam molestie sem in posuere lacinia. Morbi dictum mi nec commodo tempor. Vivamus pretium quam id ante semper, egestas porta ligula convallis. Proin placerat nibh id eros faucibus fermentum rutrum ac elit. Integer porttitor ex a purus tincidunt pretium. Curabitur tempus ipsum est, vitae hendrerit sem consectetur sed. In tincidunt, risus vel efficitur convallis, leo urna mollis risus, et dapibus ex orci eget sem. Curabitur sit amet sagittis lorem. Nullam rhoncus velit nec odio molestie, ut iaculis leo viverra. Sed viverra nunc in lobortis imperdiet. Proin quis hendrerit lorem. Etiam mauris nisl, tincidunt in laoreet et, pretium eget nunc. Curabitur quis aliquam libero, a varius enim. Curabitur eleifend rhoncus erat, quis varius ex semper non. Fusce nec sem sed nisl congue egestas.
                
                Donec ac gravida tellus, vitae pharetra eros. Morbi vestibulum in metus sit amet malesuada. Donec vestibulum faucibus efficitur. Donec elit est, pharetra at auctor in, accumsan gravida justo. Aenean pellentesque porttitor diam, id ornare libero fermentum vitae. Pellentesque euismod malesuada sodales. Ut nec gravida turpis. Vestibulum tincidunt ex ac imperdiet volutpat.
                
                Vivamus bibendum nulla id metus posuere mattis. Donec at eros tortor. Donec hendrerit nunc ante, non congue massa malesuada in. Donec eu egestas elit, sed dictum mauris. Vestibulum imperdiet ultricies diam, sed egestas nibh tempus id. Praesent condimentum nibh a auctor lacinia. Cras laoreet sit amet tortor non consequat. Etiam ac cursus nulla. Aliquam dictum ac metus ut mollis. Proin ut neque nisl. Donec mauris massa, interdum nec mollis ultrices, ultricies et lacus. Nam tincidunt, augue ac rhoncus ornare, tellus elit feugiat tortor, vitae sollicitudin magna enim quis libero.
                
                Sed facilisis cursus odio id imperdiet. Curabitur a tortor sed nibh semper viverra. Morbi vel lectus arcu. Pellentesque ut nisi orci. Quisque finibus ex risus, eget hendrerit augue pulvinar nec. Praesent elit augue, mattis ac eros ut, ornare sodales leo. In auctor scelerisque urna eu tincidunt. Nunc nunc libero, imperdiet id justo id, ultricies hendrerit nisi. Aenean quis accumsan magna, vitae cursus est. Donec blandit massa risus. Sed eu mattis mi, in luctus erat. Sed a hendrerit purus. Phasellus cursus lorem at justo condimentum, a porta leo efficitur. Nunc in nisi at tellus vulputate porttitor.
                
                Phasellus id orci pretium, venenatis sem a, lobortis erat. Pellentesque egestas facilisis fringilla. Nam fringilla lacinia massa vitae sollicitudin. Aliquam venenatis est pellentesque ultrices fermentum. Cras vestibulum ante lectus, sit amet luctus odio consequat id. Mauris egestas, libero vel blandit aliquam, ante est tristique risus, ut lobortis justo mi eget libero. Quisque vitae erat lacus. Vestibulum a leo quis diam posuere tempus. In faucibus iaculis magna eu ullamcorper. Duis faucibus justo a pharetra pellentesque. Phasellus pharetra faucibus tempor. Quisque ante lacus, accumsan ut justo vitae, faucibus congue velit.
                
                In sed cursus diam. Phasellus a condimentum turpis, ac interdum turpis. Integer fermentum arcu in nunc rutrum feugiat. Vivamus ultricies ex rhoncus dignissim posuere. Maecenas convallis ligula in ornare facilisis. Praesent ut eleifend justo. Vivamus aliquet, massa quis pellentesque molestie, nulla enim rhoncus libero, eget placerat lorem sapien id nulla. Donec ut dolor at ligula aliquet rhoncus. Proin scelerisque sapien id mollis viverra.
                
                Integer arcu dui, fringilla eu leo non, imperdiet varius quam. Morbi volutpat, risus bibendum interdum semper, massa ante imperdiet est, eu bibendum augue leo ac libero. Quisque arcu ligula, tincidunt vitae dolor in, fringilla maximus leo. Donec sagittis tortor est, nec sodales mi tincidunt vel. Nam justo lacus, interdum vel laoreet ac, rutrum ac justo. Donec nec justo lectus. Etiam vel nisl vitae massa eleifend convallis vitae ac felis. Donec vel ligula vitae nibh posuere dignissim.
                
                Nullam gravida, ex ac sollicitudin ornare, nisi mi sagittis arcu, sed blandit lacus sem nec est. In hac habitasse platea dictumst. Curabitur id sapien sed metus volutpat rhoncus ac quis lacus. Donec ut tortor viverra, blandit diam nec, eleifend nisi. Donec ultricies purus at enim tristique, sit amet sollicitudin arcu venenatis. In hac habitasse platea dictumst. Vivamus consectetur ut lorem ut molestie. Sed lacinia libero ligula, nec rutrum tellus mattis a. Ut vitae leo felis. Integer non tincidunt dolor. Phasellus felis nibh, auctor vel urna quis, dictum consectetur libero. Ut massa nisi, facilisis ultrices viverra non, aliquam sed orci. Duis porta vel elit ac aliquet.
                
                Sed sed sollicitudin justo. Sed vestibulum dui porttitor metus mattis, quis laoreet risus mollis. Sed tempor lacinia tortor nec varius. Aenean ultrices, risus at pellentesque eleifend, sapien lectus rutrum massa, id tempor orci orci vitae metus. Etiam malesuada pharetra elit quis hendrerit. Nulla id justo gravida, pretium dolor semper, sollicitudin libero. Curabitur elementum dictum orci, eu placerat eros faucibus maximus. Duis auctor nisl at arcu hendrerit pharetra. Vestibulum cursus hendrerit pulvinar.
                
                Aenean sapien tortor, gravida quis mollis fermentum, placerat ut lectus. Nam rhoncus nunc diam, sagittis rhoncus lectus condimentum congue. Pellentesque elementum dictum purus, at euismod tortor. Etiam gravida vestibulum risus, id lacinia felis vehicula et. Etiam dignissim orci ut semper tincidunt. Nam viverra facilisis pulvinar. Nulla et ipsum sem. Ut interdum sapien a vehicula pellentesque. Etiam viverra metus vel enim ultrices, eu feugiat ex sollicitudin.
                
                Nunc et vehicula dui. Vivamus consectetur tellus eget lectus venenatis, in porttitor magna egestas. Aliquam finibus elit vel arcu efficitur, non hendrerit leo semper. Suspendisse semper, risus vel fermentum rutrum, arcu neque dictum libero, eu ornare sem enim in tellus. Curabitur nec tincidunt dui. Pellentesque scelerisque cursus ullamcorper. Suspendisse semper tincidunt diam, fringilla sagittis nisi tincidunt eu. Sed ornare, dui cursus semper efficitur, nulla eros consequat enim, accumsan fermentum magna mi quis eros. Sed ipsum quam, dictum vitae tellus sed, tincidunt euismod augue. Maecenas tortor orci, aliquet quis felis quis, tristique congue diam. Vivamus laoreet nulla erat, vitae porta ligula mattis pellentesque. Praesent accumsan nibh non sapien porttitor finibus. Maecenas in interdum orci. Phasellus ultrices luctus felis, at luctus sapien fermentum ut. Nulla in risus viverra, bibendum magna id, auctor nisl.
                
                Nunc cursus venenatis magna vel consequat. Donec ut mauris eu quam commodo porttitor et at lorem. Cras facilisis eros dolor, ac imperdiet sapien aliquam eget. Morbi cursus vestibulum egestas. Mauris scelerisque quam sed cursus porttitor. Proin vehicula hendrerit eros, at blandit ante dictum vel. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec pretium sem sed ante lacinia tincidunt. Sed tristique purus vitae rutrum tincidunt. Curabitur eu auctor ante. Proin tristique rutrum arcu a placerat.
                
                Ut sodales dolor eu placerat sollicitudin. Phasellus facilisis ligula ac tempus facilisis. Sed in nibh nunc. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed elit quam, sagittis quis neque at, finibus dignissim justo. In tempor, mi ut suscipit eleifend, mi justo fringilla tellus, sed auctor diam augue finibus diam. Nulla eget tortor metus. Quisque scelerisque ex quis ipsum sollicitudin pretium. Aliquam malesuada dolor et nibh vestibulum, et aliquet mi congue. Morbi velit arcu, dapibus quis hendrerit bibendum, mattis quis massa. Curabitur sed tellus a nisl consequat fermentum vel ac est. Maecenas hendrerit mi eget neque ullamcorper eleifend. Maecenas venenatis magna quis venenatis aliquet. In hac habitasse platea dictumst.
                
                Suspendisse laoreet erat non ipsum tincidunt, eget posuere lorem lacinia. Donec ac sem diam. Nulla viverra mi quis metus egestas luctus. Quisque suscipit, erat non fermentum posuere, urna metus posuere ante, nec aliquet lorem enim id leo. Nulla libero augue, varius nec urna a, dapibus bibendum lacus. Integer tristique justo ac rutrum efficitur. Quisque odio arcu, hendrerit vitae euismod a, vehicula ac lacus. Quisque ac maximus dui, sit amet tincidunt mauris. Praesent placerat eros quis metus viverra sodales. In tempus sapien et nibh dictum blandit.
                
                Phasellus ipsum ipsum, hendrerit quis odio ut, placerat bibendum eros. Aliquam vel nisl leo. In ut ex rhoncus, pharetra lacus a, tristique ipsum. Donec ultrices accumsan ligula, eu maximus dolor. Maecenas id lectus mattis ante cursus ultrices. Donec elementum, purus id bibendum interdum, mauris elit laoreet lacus, vel semper velit metus eget mi. Fusce sodales id dui bibendum pellentesque.
                
                Maecenas tincidunt mauris felis, nec scelerisque metus maximus nec. Donec et libero sed odio porttitor scelerisque. Praesent nec mi dolor. Maecenas faucibus nibh at ante maximus, eu scelerisque libero blandit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lacinia eros at aliquam congue. Sed eu eros imperdiet, auctor justo sed, luctus ante. Aenean a ipsum dui. Sed ut felis molestie, vestibulum libero quis, tincidunt felis. Proin tortor arcu, rhoncus et mauris et, volutpat congue eros.
                
                Suspendisse ac sagittis ligula. Vestibulum dictum metus in congue placerat. Duis ultrices, enim a faucibus tincidunt, lectus lectus lacinia urna, at tempor augue turpis sit amet libero. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce vel felis ut erat malesuada lobortis. Nunc in condimentum tellus. Mauris vitae lectus sed ex fringilla vehicula. Suspendisse libero sapien, convallis id egestas id, fringilla ullamcorper arcu. Ut euismod ultrices sapien a ultrices. </p>
            
            
                </div>

                
        );
    }
}

